name: untitled
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  easy_splash_screen: ^1.0.3
  splashscreen: ^1.3.5
  google_fonts: ^2.0.0
  carousel_slider: ^4.1.1
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  cloud_firestore: ^3.1.17
  flutter_secure_storage: ^5.0.2

  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/forgot.png
    - assets/perspndrawer.png
    - assets/post.jpg
    - assets/shadow.png
    - assets/imgso.jpg


  fonts:
     - family: PlayfairDisplay
       fonts:
         - asset: assets/fonts/PlayfairDisplay-Bold.ttf
